In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)
#`hint: import … as`
import numpy as np

In [3]:
#### 2. Create a null vector of size 10 (★☆☆)
#`hint: np.zeros`
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#`hint: array[4]`
a[4] = 1
print (a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
#`hint: arange`
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#`hint: reshape`
grid = np.arange(0, 9).reshape((3, 3)) # making it a matrix 3 rows 3 colums dimension
print(grid)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#`hint: np.nonzero`
b = [1,2,0,0,4,0]
np.nonzero (b)

(array([0, 1, 4]),)

In [9]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#`hint: np.eye`
c = np.eye (3,3)
print (c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
#`hint: np.random.random`
np.random.random ((3,3,3))

array([[[0.66917644, 0.02421603, 0.32939043],
        [0.94436097, 0.98269383, 0.19533933],
        [0.88640731, 0.09331988, 0.10507587]],

       [[0.72110668, 0.64017633, 0.93394926],
        [0.62128425, 0.44398157, 0.92873363],
        [0.67819582, 0.43607733, 0.91114729]],

       [[0.65363888, 0.12996296, 0.41249226],
        [0.18702958, 0.12513975, 0.45736668],
        [0.26564939, 0.07945305, 0.78673   ]]])

In [13]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#`hint: min, max`
d = np.random.random ((10,10))
mi = np.min (d)
ma = np.max (d)
print (d)
print (mi)
print (ma)

[[0.75051628 0.1373571  0.02795334 0.00521162 0.09782662 0.25984517
  0.71660896 0.18216636 0.22473536 0.8698369 ]
 [0.90228188 0.66245818 0.74170432 0.6111339  0.42512331 0.46970668
  0.7828635  0.61017973 0.41678795 0.86061229]
 [0.62183215 0.04009819 0.36543597 0.02330736 0.71824678 0.87580139
  0.86766034 0.09374436 0.19020918 0.67164699]
 [0.89950288 0.33960642 0.80268845 0.46687144 0.94175558 0.33298607
  0.27934253 0.8229138  0.30012816 0.79564657]
 [0.20727119 0.22547612 0.82188377 0.38539169 0.76990339 0.21884956
  0.91836126 0.89840432 0.17282841 0.32573431]
 [0.68681405 0.83177078 0.43687469 0.28840984 0.35565334 0.5234664
  0.99465132 0.20714211 0.47805687 0.5599127 ]
 [0.22428102 0.07434052 0.87386128 0.23882363 0.72110565 0.40603736
  0.49690262 0.39252218 0.20182126 0.29732219]
 [0.9720058  0.77275234 0.49039664 0.69064885 0.32708176 0.27525536
  0.27625558 0.83021465 0.08432559 0.94068023]
 [0.77030036 0.7479281  0.98757916 0.11661527 0.91232613 0.68323519
  0.80411269 

In [17]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#`hint: mean`
e = np.random.random((1,30))
mean = np.mean (e)
print (e)
print (mean)

[[1.91278758e-01 6.06672664e-01 3.21799915e-01 1.67502319e-01
  5.61650378e-02 1.01701727e-01 7.24044825e-01 2.79199916e-01
  8.70790231e-01 3.54835404e-01 4.79774178e-01 9.95343940e-01
  3.38569310e-01 9.19161929e-01 5.89529999e-04 4.40644557e-01
  6.30478140e-01 2.22371719e-01 3.77509462e-01 4.46683839e-01
  8.75220796e-01 8.07675103e-01 5.65902495e-01 1.67634941e-01
  4.50359359e-01 1.72030511e-01 9.21313459e-01 7.21725724e-01
  9.76259048e-01 5.86356275e-01]]
0.49231983696743686


In [22]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#`hint: np.diag`
f = np.zeros((5,5))
print (f)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
diag_f = [1,2,3,4]
np.diag(f, 1)

array([0., 0., 0., 0.])

In [28]:
np.fill_diagonal(f[1:], diag_f)
print (f)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [44]:
g = np.diag(np.arange(1,5),-1)
print (g)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [35]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#`hint: (x -mean)/std`
x = np.random.random ((5,5))
mean = np.mean (x)
std = np.std (x)
normal_x = (x - mean)/std
print ('x', x)
print ('normal_x',normal_x)

x [[0.49248349 0.46280385 0.26190499 0.57860189 0.12769585]
 [0.81774095 0.27554912 0.71407919 0.94794189 0.86028453]
 [0.8353774  0.91532042 0.6909823  0.01741026 0.71380697]
 [0.1412406  0.8082221  0.70847238 0.92760188 0.993987  ]
 [0.55652396 0.12070325 0.59153894 0.50088774 0.42580312]]
normal_x [[-0.30546946 -0.40968483 -1.11510943 -0.00307829 -1.58636364]
 [ 0.83662074 -1.06720024  0.47262885  1.29380076  0.98600581]
 [ 0.89854833  1.17925562  0.39152775 -1.97361406  0.471673  ]
 [-1.53880338  0.8031968   0.45294142  1.22238002  1.4554809 ]
 [-0.08060144 -1.61091704  0.04234811 -0.27595925 -0.53960704]]


In [37]:
#### 13. How to find common values between two arrays? (★☆☆)
#`hint: np.intersect1d`
np.intersect1d([1, 3, 4, 5], [3, 1, 5, 1])

array([1, 3, 5])

In [40]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#`hint: sort`
y = np.random.random ((1,10))
print (y)

[[0.13639457 0.06678555 0.47902866 0.83707006 0.59336585 0.21815909
  0.39944296 0.40053022 0.86451462 0.19359332]]


In [41]:
np.sort (y)

array([[0.06678555, 0.13639457, 0.19359332, 0.21815909, 0.39944296,
        0.40053022, 0.47902866, 0.59336585, 0.83707006, 0.86451462]])

In [54]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#`hint: argmax`
h = np.random.random ((1,10))
print (h)
print (np.argmax (h))

[[0.31043379 0.1812132  0.34419267 0.34834224 0.93559041 0.26952477
  0.21384841 0.06508205 0.0276659  0.98387389]]
9


In [56]:
h[0,9] = 0
h

array([[0.        , 0.1812132 , 0.34419267, 0.34834224, 0.93559041,
        0.26952477, 0.21384841, 0.06508205, 0.0276659 , 0.        ]])

In [58]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#`hint: mean(axis=,keepdims=)
l = np.random.random ((3,4))
l

array([[0.95622006, 0.30723019, 0.36464441, 0.68731218],
       [0.47191489, 0.45493942, 0.68808849, 0.47435944],
       [0.05583325, 0.79027792, 0.74974573, 0.00246574]])

In [59]:
m = l - l.mean (axis=1,keepdims=True)
m

array([[ 0.37736835, -0.27162152, -0.2142073 ,  0.10846047],
       [-0.05041067, -0.06738614,  0.16576293, -0.04796612],
       [-0.34374741,  0.39069726,  0.35016507, -0.39711492]])

In [66]:
#### 17. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
#hint: np.argsort | np.argpartition
Z_sorted = np.argsort(Z)
rslt = Z_sorted[-n : ]
rslt

array([4588, 3792, 6628, 3255, 5361])

In [69]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#`hint: np.where`
k = np.random.random ((5,3))
np.where(k > 4, k, k**2)

array([[0.38571272, 0.12398935, 0.04950723],
       [0.46713046, 0.0780621 , 0.71792196],
       [0.28625629, 0.00205823, 0.29556239],
       [0.57538797, 0.06187049, 0.17771021],
       [0.81848275, 0.96938867, 0.00366402]])