In [2]:
#### 1. Import the numpy package under the name `np` (★☆☆)
#`hint: import … as`
import numpy as np

In [3]:
#### 2. Create a null vector of size 10 (★☆☆)
#`hint: np.zeros`
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#`hint: array[4]`
a[4] = 1
print (a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
#`hint: arange`
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#`hint: reshape`
grid = np.arange(0, 9).reshape((3, 3)) # making it a matrix 3 rows 3 colums dimension
print(grid)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#`hint: np.nonzero`
b = [1,2,0,0,4,0]
np.nonzero (b)

(array([0, 1, 4]),)

In [8]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#`hint: np.eye`
c = np.eye (3,3)
print (c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
#`hint: np.random.random`
np.random.random ((3,3,3))

array([[[6.74333025e-01, 3.25372108e-01, 6.81720653e-01],
        [7.15516102e-01, 7.60873222e-01, 7.77964511e-01],
        [9.54919209e-01, 3.02079738e-01, 2.52140820e-01]],

       [[6.89893906e-01, 8.84989588e-01, 1.55877269e-01],
        [6.35043966e-01, 4.30543032e-01, 6.74372151e-01],
        [9.35772842e-01, 7.17601512e-02, 4.61753965e-04]],

       [[3.51064037e-01, 4.87068988e-01, 4.99164310e-01],
        [3.02530215e-01, 2.50986440e-01, 7.02857435e-01],
        [1.63433454e-01, 8.45631007e-01, 1.03887093e-01]]])

In [10]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#`hint: min, max`
d = np.random.random ((10,10))
mi = np.min (d)
ma = np.max (d)
print (d)
print (mi)
print (ma)

[[0.99020309 0.86374472 0.62627634 0.39084451 0.89025619 0.4646976
  0.8278434  0.27095399 0.31218037 0.80938454]
 [0.610126   0.76881824 0.06197998 0.57309451 0.15424914 0.41588253
  0.19412552 0.07213951 0.75891668 0.24213441]
 [0.89613803 0.82901632 0.57756906 0.7484569  0.70755168 0.47340494
  0.89956629 0.04236212 0.91583221 0.59810841]
 [0.74950463 0.74259011 0.18234164 0.75134091 0.59454378 0.98056505
  0.01182691 0.32496185 0.18370499 0.27650455]
 [0.13268446 0.69815494 0.5835767  0.18953921 0.73658234 0.29063573
  0.25779865 0.73960673 0.52705707 0.05654636]
 [0.8880243  0.37936638 0.43716198 0.40007801 0.53938231 0.65688433
  0.30494355 0.75094877 0.92051335 0.39295498]
 [0.92630327 0.68382394 0.6415839  0.34356952 0.15312194 0.81239556
  0.72989807 0.01458518 0.3695242  0.38920095]
 [0.92729602 0.21359061 0.45736551 0.62172391 0.36767763 0.36975289
  0.83269543 0.88698026 0.53929813 0.98818664]
 [0.17973809 0.16095887 0.58674074 0.40967136 0.73987176 0.85093982
  0.92272787 

In [11]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#`hint: mean`
e = np.random.random((1,30))
mean = np.mean (e)
print (e)
print (mean)

[[0.1993863  0.88766483 0.18496058 0.49065506 0.54218279 0.10255899
  0.40336988 0.15007443 0.48919292 0.34479647 0.53593842 0.63469607
  0.88641145 0.61187837 0.83150203 0.35221676 0.6913369  0.46197284
  0.43948454 0.73203887 0.28303209 0.57136727 0.06269176 0.73342148
  0.1920139  0.11801618 0.41973819 0.75979766 0.83127224 0.10092983]]
0.4681533032182004


In [12]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#`hint: np.diag`
f = np.zeros((5,5))
print (f)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
diag_f = [1,2,3,4]
np.diag(f, 1)

array([0., 0., 0., 0.])

In [14]:
np.fill_diagonal(f[1:], diag_f)
print (f)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [15]:
g = np.diag(np.arange(1,5),-1)
print (g)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [16]:
help(np.diag)

Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input 

In [35]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#`hint: (x -mean)/std`
x = np.random.random ((5,5))
mean = np.mean (x)
std = np.std (x)
normal_x = (x - mean)/std
print ('x', x)
print ('normal_x',normal_x)

x [[0.49248349 0.46280385 0.26190499 0.57860189 0.12769585]
 [0.81774095 0.27554912 0.71407919 0.94794189 0.86028453]
 [0.8353774  0.91532042 0.6909823  0.01741026 0.71380697]
 [0.1412406  0.8082221  0.70847238 0.92760188 0.993987  ]
 [0.55652396 0.12070325 0.59153894 0.50088774 0.42580312]]
normal_x [[-0.30546946 -0.40968483 -1.11510943 -0.00307829 -1.58636364]
 [ 0.83662074 -1.06720024  0.47262885  1.29380076  0.98600581]
 [ 0.89854833  1.17925562  0.39152775 -1.97361406  0.471673  ]
 [-1.53880338  0.8031968   0.45294142  1.22238002  1.4554809 ]
 [-0.08060144 -1.61091704  0.04234811 -0.27595925 -0.53960704]]


In [37]:
#### 13. How to find common values between two arrays? (★☆☆)
#`hint: np.intersect1d`
np.intersect1d([1, 3, 4, 5], [3, 1, 5, 1])

array([1, 3, 5])

In [17]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#`hint: sort`
y = np.random.random ((1,10))
print (y)

[[0.25189014 0.71086111 0.37984783 0.50666471 0.50694948 0.45569009
  0.76748999 0.44716638 0.1247483  0.30773856]]


In [18]:
np.sort (y)

array([[0.1247483 , 0.25189014, 0.30773856, 0.37984783, 0.44716638,
        0.45569009, 0.50666471, 0.50694948, 0.71086111, 0.76748999]])

In [19]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#`hint: argmax`
h = np.random.random ((1,10))
print (h)
print (np.argmax (h))

[[0.91171415 0.41162902 0.81423634 0.90620494 0.17667379 0.64268392
  0.86918178 0.50261996 0.9563909  0.06966945]]
8


In [20]:
h[0,9] = 0
h

array([[0.91171415, 0.41162902, 0.81423634, 0.90620494, 0.17667379,
        0.64268392, 0.86918178, 0.50261996, 0.9563909 , 0.        ]])

In [22]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#`hint: mean(axis=,keepdims=)
l = np.random.random ((3,4))
l

array([[0.66793672, 0.80862872, 0.26896033, 0.53232684],
       [0.03081691, 0.63498142, 0.14868841, 0.90207648],
       [0.6365916 , 0.16817391, 0.05577547, 0.12788579]])

In [30]:
m = l - l.mean (axis=1,keepdims=True) # axis = 0 is colums and axis = 1 is rows - keepdims is keep dimensions
m

array([[ 0.09847357,  0.23916557, -0.30050282, -0.03713632],
       [-0.3983239 ,  0.20584062, -0.28045239,  0.47293567],
       [ 0.38948491, -0.07893278, -0.19133122, -0.1192209 ]])

In [34]:
#### 17. How to get the n largest values of an array (★★★)
#Z = np.arange(10000)
#np.random.shuffle(Z)
#n = 5
#hint: np.argsort | np.argpartition
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n : ]]) # argsort doesn't give you the sorted values but it gives you the index of the sorted values

[9995 9996 9997 9998 9999]


In [69]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#`hint: np.where`
k = np.random.random ((5,3))
np.where(k > 4, k, k**2)

array([[0.38571272, 0.12398935, 0.04950723],
       [0.46713046, 0.0780621 , 0.71792196],
       [0.28625629, 0.00205823, 0.29556239],
       [0.57538797, 0.06187049, 0.17771021],
       [0.81848275, 0.96938867, 0.00366402]])